import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Suprimir errores de extensiones de navegador
              window.addEventListener('error', function(e) {
                if (e.filename && e.filename.includes('chrome-extension://')) {
                  e.preventDefault();
                  return false;
                }
              });
              
              // Suprimir errores de MetaMask y otras extensiones Web3
              window.addEventListener('unhandledrejection', function(e) {
                if (e.reason && typeof e.reason === 'object') {
                  if (e.reason.message && (
                    e.reason.message.includes('MetaMask') ||
                    e.reason.message.includes('chrome-extension') ||
                    e.reason.message.includes('ethereum')
                  )) {
                    e.preventDefault();
                    return false;
                  }
                }
              });
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
